#!/usr/bin/env lua5.2

local fpipe = require 'filterpipe'
local P = {}

function P.echo(i, ...) return fpipe(i, "echo", ...) end
function P.dir(i, ...) return fpipe(i, "dir", ...) end
function P.rmdir(i, ...) return fpipe(i, "rmdir", ...) end
function P.chgrp(i, ...) return fpipe(i, "chgrp", ...) end
function P.readlink(i, ...) return fpipe(i, "readlink", ...) end
function P.pwd(i, ...) return fpipe(i, "pwd", ...) end
function P.mkdir(i, ...) return fpipe(i, "mkdir", ...) end
function P.chmod(i, ...) return fpipe(i, "chmod", ...) end
function P.df(i, ...) return fpipe(i, "df", ...) end
function P.date(i, ...) return fpipe(i, "date", ...) end
function P.stty(i, ...) return fpipe(i, "stty", ...) end
function P.uname(i, ...) return fpipe(i, "uname", ...) end
function P.sleep(i, ...) return fpipe(i, "sleep", ...) end
function P.mktemp(i, ...) return fpipe(i, "mktemp", ...) end
function P.rm(i, ...) return fpipe(i, "rm", ...) end
function P.vdir(i, ...) return fpipe(i, "vdir", ...) end
function P.touch(i, ...) return fpipe(i, "touch", ...) end
function P.ls(i, ...) return fpipe(i, "ls", ...) end
function P.sync(i, ...) return fpipe(i, "sync", ...) end
function P.ln(i, ...) return fpipe(i, "ln", ...) end
function P.mv(i, ...) return fpipe(i, "mv", ...) end
function P.dd(i, ...) return fpipe(i, "dd", ...) end
function P.cat(i, ...) return fpipe(i, "cat", ...) end
function P.cp(i, ...) return fpipe(i, "cp", ...) end
function P.mknod(i, ...) return fpipe(i, "mknod", ...) end
function P.chown(i, ...) return fpipe(i, "chown", ...) end
function P.env(i, ...) return fpipe(i, "env", ...) end
function P.sha1sum(i, ...) return fpipe(i, "sha1sum", ...) end
function P.ptx(i, ...) return fpipe(i, "ptx", ...) end
function P.tr(i, ...) return fpipe(i, "tr", ...) end
function P.sum(i, ...) return fpipe(i, "sum", ...) end
function P.seq(i, ...) return fpipe(i, "seq", ...) end
function P.base64(i, ...) return fpipe(i, "base64", ...) end
function P.sort(i, ...) return fpipe(i, "sort", ...) end
function P.who(i, ...) return fpipe(i, "who", ...) end
function P.sha384sum(i, ...) return fpipe(i, "sha384sum", ...) end
function P.tac(i, ...) return fpipe(i, "tac", ...) end
function P.printf(i, ...) return fpipe(i, "printf", ...) end
function P.expand(i, ...) return fpipe(i, "expand", ...) end
function P.install(i, ...) return fpipe(i, "install", ...) end
function P.wc(i, ...) return fpipe(i, "wc", ...) end
function P.tail(i, ...) return fpipe(i, "tail", ...) end
function P.groups(i, ...) return fpipe(i, "groups", ...) end
function P.printenv(i, ...) return fpipe(i, "printenv", ...) end
function P.id(i, ...) return fpipe(i, "id", ...) end
function P.cksum(i, ...) return fpipe(i, "cksum", ...) end
function P.sha256sum(i, ...) return fpipe(i, "sha256sum", ...) end
function P.yes(i, ...) return fpipe(i, "yes", ...) end
function P.hostid(i, ...) return fpipe(i, "hostid", ...) end
function P.basename(i, ...) return fpipe(i, "basename", ...) end
function P.truncate(i, ...) return fpipe(i, "truncate", ...) end
function P.logname(i, ...) return fpipe(i, "logname", ...) end
function P.sha512sum(i, ...) return fpipe(i, "sha512sum", ...) end
function P.shred(i, ...) return fpipe(i, "shred", ...) end
function P.test(i, ...) return fpipe(i, "test", ...) end
function P.comm(i, ...) return fpipe(i, "comm", ...) end
function P.chcon(i, ...) return fpipe(i, "chcon", ...) end
function P.csplit(i, ...) return fpipe(i, "csplit", ...) end
function P.dircolors(i, ...) return fpipe(i, "dircolors", ...) end
function P.uniq(i, ...) return fpipe(i, "uniq", ...) end
function P.cut(i, ...) return fpipe(i, "cut", ...) end
function P.pinky(i, ...) return fpipe(i, "pinky", ...) end
function P.head(i, ...) return fpipe(i, "head", ...) end
function P.stat(i, ...) return fpipe(i, "stat", ...) end
function P.split(i, ...) return fpipe(i, "split", ...) end
function P.dirname(i, ...) return fpipe(i, "dirname", ...) end
function P.mkfifo(i, ...) return fpipe(i, "mkfifo", ...) end
function P.expr(i, ...) return fpipe(i, "expr", ...) end
function P.tee(i, ...) return fpipe(i, "tee", ...) end
function P.nice(i, ...) return fpipe(i, "nice", ...) end
function P.join(i, ...) return fpipe(i, "join", ...) end
function P.runcon(i, ...) return fpipe(i, "runcon", ...) end
function P.nproc(i, ...) return fpipe(i, "nproc", ...) end
function P.link(i, ...) return fpipe(i, "link", ...) end
function P.tty(i, ...) return fpipe(i, "tty", ...) end
function P.tsort(i, ...) return fpipe(i, "tsort", ...) end
function P.nohup(i, ...) return fpipe(i, "nohup", ...) end
function P.stdbuf(i, ...) return fpipe(i, "stdbuf", ...) end
function P.shuf(i, ...) return fpipe(i, "shuf", ...) end
function P.fmt(i, ...) return fpipe(i, "fmt", ...) end
function P.od(i, ...) return fpipe(i, "od", ...) end
function P.pathchk(i, ...) return fpipe(i, "pathchk", ...) end
function P.whoami(i, ...) return fpipe(i, "whoami", ...) end
function P.sha224sum(i, ...) return fpipe(i, "sha224sum", ...) end
function P.pr(i, ...) return fpipe(i, "pr", ...) end
function P.nl(i, ...) return fpipe(i, "nl", ...) end
function P.fold(i, ...) return fpipe(i, "fold", ...) end
function P.arch(i, ...) return fpipe(i, "arch", ...) end
function P.unexpand(i, ...) return fpipe(i, "unexpand", ...) end
function P.unlink(i, ...) return fpipe(i, "unlink", ...) end
function P.timeout(i, ...) return fpipe(i, "timeout", ...) end
function P.factor(i, ...) return fpipe(i, "factor", ...) end
function P.numfmt(i, ...) return fpipe(i, "numfmt", ...) end
function P.md5sum(i, ...) return fpipe(i, "md5sum", ...) end
function P.users(i, ...) return fpipe(i, "users", ...) end
function P.paste(i, ...) return fpipe(i, "paste", ...) end
function P.du(i, ...) return fpipe(i, "du", ...) end
function P.touch(i, ...) return fpipe(i, "touch", ...) end
function P.sed(i, ...) return fpipe(i, "sed", ...) end

setmetatable(P, { __call = function (t, ...) return fpipe(...) end })
return P
